"""
generate_data.py
Generates data.sql with Indian sample data for hotel_db:
  1 hotel, 4 room types, 300 rooms, 1000+ guests, reservations, payments.
Usage:  python generate_data.py          (creates data.sql)
Change NUM_GUESTS / NUM_RESERVATIONS below if you want more rows.
All phone numbers and ID numbers are random/masked, not real people.
"""
import random
from datetime import date, timedelta

random.seed(42)  # same data every run; remove for fresh random data

NUM_GUESTS = 1200
NUM_RESERVATIONS = 1500

first_male = ["Rahul", "Amit", "Arjun", "Vikram", "Rohan", "Karan", "Sandeep", "Manish",
              "Suresh", "Rajesh", "Deepak", "Ankit", "Nitin", "Varun", "Harsh", "Mohammed",
              "Faiz", "Gurpreet", "Harpreet", "Siddharth", "Aditya", "Pranav", "Yash", "Vivek",
              "Abhishek", "Ravi", "Naveen", "Kiran", "Sachin", "Tarun"]
first_female = ["Priya", "Ananya", "Sneha", "Pooja", "Neha", "Kavya", "Divya", "Meera",
                "Anjali", "Shreya", "Riya", "Isha", "Nisha", "Swati", "Aishwarya", "Lakshmi",
                "Sunita", "Rekha", "Fatima", "Simran", "Jasleen", "Tanvi", "Komal", "Radha",
                "Bhavna", "Preeti", "Shruti", "Nandini", "Deepika", "Mansi"]
surnames = ["Sharma", "Patel", "Reddy", "Iyer", "Singh", "Deshmukh", "Verma", "Gupta",
            "Joshi", "Nair", "Khan", "Mehta", "Agarwal", "Chauhan", "Yadav", "Pillai",
            "Banerjee", "Chatterjee", "Das", "Mukherjee", "Kulkarni", "Jain", "Bhatt",
            "Rathore", "Tiwari", "Mishra", "Pandey", "Naidu", "Menon", "Kapoor", "Malhotra",
            "Thakur", "Saxena", "Shetty", "Gill", "Bose", "Rao", "Pawar", "Shukla", "Ansari"]

# (city, state)
places = [("Indore", "Madhya Pradesh"), ("Bhopal", "Madhya Pradesh"), ("Jaipur", "Rajasthan"),
          ("Udaipur", "Rajasthan"), ("Pune", "Maharashtra"), ("Mumbai", "Maharashtra"),
          ("Nagpur", "Maharashtra"), ("Chennai", "Tamil Nadu"), ("Coimbatore", "Tamil Nadu"),
          ("Kolkata", "West Bengal"), ("Hyderabad", "Telangana"), ("Bengaluru", "Karnataka"),
          ("Mysuru", "Karnataka"), ("Kochi", "Kerala"), ("Thiruvananthapuram", "Kerala"),
          ("Ahmedabad", "Gujarat"), ("Surat", "Gujarat"), ("Vadodara", "Gujarat"),
          ("Delhi", "Delhi"), ("Lucknow", "Uttar Pradesh"), ("Varanasi", "Uttar Pradesh"),
          ("Kanpur", "Uttar Pradesh"), ("Patna", "Bihar"), ("Chandigarh", "Chandigarh"),
          ("Amritsar", "Punjab"), ("Ludhiana", "Punjab"), ("Bhubaneswar", "Odisha"),
          ("Guwahati", "Assam"), ("Ranchi", "Jharkhand"), ("Raipur", "Chhattisgarh"),
          ("Dehradun", "Uttarakhand"), ("Visakhapatnam", "Andhra Pradesh"), ("Panaji", "Goa")]

id_types = ["Aadhaar", "PAN", "Voter ID", "Driving Licence"]
email_domains = ["gmail.com", "yahoo.in", "outlook.com", "rediffmail.com"]

hotels = [
    ("AthitiStay", "12 Rajwada Road", "Indore", "Mr. Ramesh Chandra"),
]
room_types = [("Single", 600), ("Double", 1000), ("Triple", 1400),
              ("Deluxe AC", 2000), ("Duplex", 3000)]
capacities = [1, 2, 3, 2, 4]

def esc(s):
    return s.replace("'", "''")

out = []
out.append("-- Auto-generated by generate_data.py\nUSE hotel_db;\n")

# Hotels
out.append("INSERT INTO Hotel (hotel_name, address, city, manager_name) VALUES")
out.append(",\n".join(f"('{esc(n)}', '{esc(a)}', '{c}', '{esc(w)}')" for n, a, c, w in hotels) + ";\n")

# Room types
out.append("INSERT INTO RoomType (type_name, rent_per_day) VALUES")
out.append(",\n".join(f"('{n}', {r})" for n, r in room_types) + ";\n")

# Rooms: 300 rooms in the single hotel; room_id k has type ((k-1) % 4) + 1
rooms = []
rid = 0
for h in range(1, len(hotels) + 1):
    for n in range(1, 301):
        rid += 1
        t = (rid - 1) % len(room_types) + 1
        rooms.append((rid, h, t, f"{h}0{n}", capacities[t - 1]))
out.append("INSERT INTO Room (hotel_id, type_id, room_no, capacity, status) VALUES")
out.append(",\n".join(f"({h}, {t}, '{no}', {cap}, 'Available')" for _, h, t, no, cap in rooms) + ";\n")

# Guests
used_emails, used_phones = set(), set()
guests = []
for i in range(1, NUM_GUESTS + 1):
    female = random.random() < 0.45
    first = random.choice(first_female if female else first_male)
    last = random.choice(surnames)
    name = f"{first} {last}"
    email = f"{first.lower()}.{last.lower()}{i}@{random.choice(email_domains)}"
    while True:
        phone = str(random.choice([6, 7, 8, 9])) + "".join(random.choice("0123456789") for _ in range(9))
        if phone not in used_phones:
            used_phones.add(phone)
            break
    city, state = random.choice(places)
    idt = random.choice(id_types)
    idno = f"XXXX-XXXX-{random.randint(1000, 9999)}"
    guests.append((name, phone, email, city, state, idt, idno))

out.append("INSERT INTO Guest (name, phone, email, city, state, id_proof_type, id_proof_no) VALUES")
rows = [f"('{esc(n)}', '{p}', '{e}', '{c}', '{s}', '{t}', '{no}')" for n, p, e, c, s, t, no in guests]
out.append(",\n".join(rows) + ";\n")

# Reservations + payments
statuses = ["Booked", "Checked-in", "Cancelled", "Completed"]
weights = [15, 10, 10, 65]
modes = ["Cash", "UPI", "Card", "Net Banking"]
mode_w = [20, 55, 15, 10]
start = date(2025, 1, 1)
res_rows, pay_rows = [], []
for r in range(1, NUM_RESERVATIONS + 1):
    guest = random.randint(1, NUM_GUESTS)
    room_id, _, t, _, _ = random.choice(rooms)
    cin = start + timedelta(days=random.randint(0, 640))
    days = random.randint(1, 10)
    cout = cin + timedelta(days=days)
    status = random.choices(statuses, weights)[0]
    res_rows.append(f"({guest}, {room_id}, '{cin}', '{cout}', '{status}')")
    if status != "Cancelled":
        amount = days * room_types[t - 1][1]
        pay_rows.append(f"({r}, {amount}.00, '{cin}', '{random.choices(modes, mode_w)[0]}')")

out.append("INSERT INTO Reservation (guest_id, room_id, check_in, check_out, status) VALUES")
out.append(",\n".join(res_rows) + ";\n")
out.append("INSERT INTO Payment (reservation_id, amount, payment_date, mode) VALUES")
out.append(",\n".join(pay_rows) + ";\n")

with open("data.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(out))

print(f"data.sql created: {NUM_GUESTS} guests, {NUM_RESERVATIONS} reservations, {len(pay_rows)} payments")
